name: Test package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create Hebigo package
      run: |
        pip install setuptools
        python setup.py sdist
    - name: Install Hebigo package from dist/
      run: |
        pip install dist/*
    - name: Test install with pytest (including doctests)
      run: |
        python -c "import tests"  # Compiles hissp.basic on package import.
        pytest -v --cov=hissp --cov-report=xml --doctest-modules --doctest-glob *.md --doctest-glob *.rst tests/ docs/ $(python -c "import hebi; print(hebi.__path__[0])")

